### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by dschnare** [alphakennyn/TrexityTest#1]
Hey @alphakennyn, I can't seem to install this dependency. Oddly, other sites load in my browser and don't have any known internet connectivity issues. Tried testing `curL` as well with a known website and no problems. Looks like an artifact from JFrog is trying to be downloaded?

![image](https://user-images.githubusercontent.com/893365/150653918-29430454-cb7c-4a64-a579-6c87ba83329a.png)

**Comment by alphakennyn** [comment]
Hi @dschnare I realised I downloaded my packages from my company's artifactory. To get around this, you can actually just delete `package-lock.json` and run `npm i` again. This should install the packages not from the artifactory.

I also noticed there was a typo in my script; to run the frontend side, just run `npm start`.

**Comment by dschnare** [comment]
Thanks!
